echo "t0 = $(sudo cat ~/bitcoin/bitcoin_client2/data/debug.log |grep 'UpdateTip: new best'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "t1 = $(sudo cat ~/bitcoin/bitcoin_client2/data/debug.log |grep 'ADV'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+')" 
echo "t2 = $(sudo cat ~/bitcoin/bitcoin_client2/data/debug.log |grep 'CTR'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "t3 = $(sudo cat ~/bitcoin/bitcoin_master/data/debug.log |grep 'connection.*accepted'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "t4 = $(sudo cat ~/bitcoin/bitcoin_master/data/debug.log |grep 'UpdateTip: new best'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "t5 = $(sudo cat ~/bitcoin/bitcoin_master/data/debug.log |grep 'BLK'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|tail -n1)" 
echo "t6 = $(sudo cat ~/bitcoin/bitcoin_master/data/debug.log |grep 'INV'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|tail -n1)"
echo "t7 = $(sudo cat ~/bitcoin/bitcoin_client/data/debug.log |grep 'RINV'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "t8 = $(sudo cat ~/bitcoin/bitcoin_client/data/debug.log |grep 'Relay: Block finished'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "t9 = $(sudo cat ~/bitcoin/bitcoin_client/data/debug.log |grep 'UpdateTip: new best'|grep -o '[0-9]\+:[0-9]\+:[0-9.]\+'|head -n1)"
echo "size = $(sudo cat ~/bitcoin/bitcoin_master/data/debug.log |grep 'Relay: send block hash'|sed -e "s/^.*size=//g"|grep -o '^[0-9.]\+'|head -n1)"
